-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 18:33:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_kurse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_kurse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_kurse` DEFAULT CHARACTER SET utf8 ;
USE `db_kurse` ;

-- -----------------------------------------------------
-- Table `db_kurse`.`tbl_internal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurse`.`tbl_internal` (
  `internal_id` INT NOT NULL AUTO_INCREMENT,
  `Vorname` VARCHAR(45) NULL,
  `Nachname` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  `PLZ` VARCHAR(45) NULL,
  `Admin` TINYINT NULL,
  `Bezeichnung` VARCHAR(45) NULL,
  `internal_username` VARCHAR(45) NULL,
  `internal_password` VARCHAR(255) NULL,
  PRIMARY KEY (`internal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_kurse`.`tbl_kurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurse`.`tbl_kurs` (
  `Kurs_ID` INT NOT NULL AUTO_INCREMENT,
  `Kursbezeichnung` VARCHAR(45) NULL,
  `Datum` DATE NULL,
  `tbl_internal_internal_id` INT NOT NULL,
  PRIMARY KEY (`Kurs_ID`, `tbl_internal_internal_id`),
  INDEX `fk_Kurse_tbl_internal_idx` (`tbl_internal_internal_id` ASC) VISIBLE,
  CONSTRAINT `fk_Kurse_tbl_internal`
    FOREIGN KEY (`tbl_internal_internal_id`)
    REFERENCES `db_kurse`.`tbl_internal` (`internal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_kurse`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurse`.`tbl_user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `Vorname` VARCHAR(45) NULL,
  `Nachname` VARCHAR(45) NULL,
  `Addresse` VARCHAR(45) NULL,
  `PLZ` VARCHAR(45) NULL,
  `Geburtsdatum` DATE NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `tbl_kurs_Kurs_ID` INT NOT NULL,
  PRIMARY KEY (`user_id`, `tbl_kurs_Kurs_ID`),
  INDEX `fk_tbl_user_tbl_kurs1_idx` (`tbl_kurs_Kurs_ID` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_user_tbl_kurs1`
    FOREIGN KEY (`tbl_kurs_Kurs_ID`)
    REFERENCES `db_kurse`.`tbl_kurs` (`Kurs_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_kurse`.`tbl_docs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kurse`.`tbl_docs` (
  `doc_id` INT NOT NULL AUTO_INCREMENT,
  `Bezeichnung` VARCHAR(45) NULL,
  `Pfad` VARCHAR(45) NULL,
  `tbl_kurs_Kurs_ID` INT NOT NULL,
  PRIMARY KEY (`doc_id`, `tbl_kurs_Kurs_ID`),
  INDEX `fk_tbl_docs_tbl_kurs1_idx` (`tbl_kurs_Kurs_ID` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_docs_tbl_kurs1`
    FOREIGN KEY (`tbl_kurs_Kurs_ID`)
    REFERENCES `db_kurse`.`tbl_kurs` (`Kurs_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
